id: TwitterAPI
key: TwitterAPI
name: Twitter API
description: Provides support for the Twitter API.
plugin_author: Byrne Reese
schema_version: 1.1

config_settings:
  TwitterAPIScript:
    default: twitter.cgi

applications:
  twitter_api:
    handler: 'Melody::API::Twitter'

object_types:
    tw_favorite: Melody::Favorite
    tw_follower: Melody::Follower

callbacks:
  MT::Entry::post_remove: Melody::API::Twitter::Callbacks::entry_post_remove
  MT::Author::post_remove: Melody::API::Twitter::Callbacks::author_post_remove
